name:                yacht
version:             1.2.0.0

dependencies:
  - base

library:
  exposed-modules: Yacht
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - containers

tests:
  test:
    main:        Tests.hs
    source-dirs: test
    dependencies:
    - yacht
    - hspec
