name: lens-person
version: 0.1.0.3

dependencies:
  - base
  - time

library:
  exposed-modules: Person
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - lens
  - lens-datetime
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - lens-person
      - hspec
