name: zebra-puzzle
version: 0.1.0.2

dependencies:
  - base

library:
  exposed-modules: ZebraPuzzle
  source-dirs: src
  dependencies:
    - containers
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - zebra-puzzle
      - hspec
