#!/bin/sh

echo
echo "---- pycodestyle ----"
pycodestyle ${HOME}/exercism/python/ --filename=*.py --exclude=*_test.py

echo
echo "---- pylint ----"
pylint -r n $(find ${HOME}/exercism/python/ -name '*.py' \
                   -not -name '*_test.py')
