[package]
edition = "2018"
name = "alphametics"
version = "1.3.0"

[dependencies]
regex = "=1.5.5"
lazy_static = "1.2"
bitflags = "=1.3.2"
counter = "=0.5.5"

aho-corasick = "=0.7.18"
regex-syntax = "=0.6.25"
