name: go-counting
version: 1.0.0.4

dependencies:
  - base
  - containers
  - array

library:
  exposed-modules: Counting
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - containers
    - array

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - go-counting
      - hspec
