name: sublist
version: 1.0.0.3

dependencies:
  - base

library:
  exposed-modules: Sublist
  source-dirs: src
  dependencies:
    - vector
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sublist
      - hspec
