name: dominoes
version: 2.1.0.9

dependencies:
  - base

library:
  exposed-modules: Dominoes
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - containers
    - multiset
    - safe
    - extra
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - dominoes
      - hspec
