name: dominoes
version: 2.1.0.7

dependencies:
  - base

library:
  exposed-modules: Dominoes
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - multiset
  - safe
  - extra

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - dominoes
      - hspec
