#!/bin/bash

for d in /home/harrison/exercism/lisp/*; do
    # echo $d
    # if ! (echo $d | grep -q hamming); then
    #     continue
    # fi
    (
        cd "$d"
        echo
        echo "---- ${d##*/} ----"
        test=$(ls *-test.lisp)
        # echo "test: \"$test\""
        source=$(ls *.lisp | grep -v "$test")
        # echo "source: \"$source\""
        # test="$f"
        # source="${f%%-test*}"
        compile="(compile-file \"${source}\")"
        test="(load \"${test}\")"
        command="(progn ${compile} ${test} (quit))"
        # echo "command: $command"
        sbcl --noinform --eval "$command"
    )
done
         
